//
// Created by W-Mai on 2023/2/22.
//

#include "ObjBase.h"

#define CURRENT_CLASS_NAME ObjBase

MAP_TYPE<FUNC_ENUM_NAME(CURRENT_CLASS_NAME), void (CURRENT_CLASS_NAME::*)()>
    CURRENT_CLASS_NAME::FUNC_MAP_NAME;
MAP_TYPE<ATTR_ENUM_NAME(CURRENT_CLASS_NAME), ObjBase_ATTR_FUNC_PACK>
    CURRENT_CLASS_NAME::ATTR_MAP_NAME;
